version: "3.8"

services:
  postgres:
    image: postgres:14.10
    restart: always
    container_name: postgresql
    volumes: 
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=LST
      - POSTGRES_PASSWORD=LST
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=LST@admin.com
      - PGADMIN_DEFAULT_PASSWORD=LST
    ports:
      - "5431:80"
    depends_on:
      - postgres

  web:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes: 
      - .:/code
    ports:
      - "8083:8000"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=LST
      - POSTGRES_PASSWORD=LST
    depends_on:
      - postgres

#Change this to host folder on linux/unix OS, on windows there is trouble with folder permission and Docker volume is recomended (That is why I used it this way)
volumes:
  pgdata:
