from django.db.models.signals import post_migrate
from django.dispatch import receiver
from ..models import Stock_Type, Item_status, Purchase_status, Location, Zone, Telescope, Unit, Payment_sources, Category, Sub_category, Group, Telescope_structure
from django.contrib.auth.models import Group as G, Permission, User

def run():

    ItemStatuses_entries = [
        {'name': 'Purchased'},
        {'name': 'Stored'},
        {'name': 'Broken'},
        {'name': 'Unmanaged'},
        {'name': 'In use'},
    ]
    PurchaseStatuses_entries = [
        {'name': 'Purchased'},
        {'name': 'Received'},
    ]
    StockTypes_entries = [
        {'name': 'Stock In'},
        {'name': 'Stock Out'},
    ]
    Location_zones_entries = [
        {0: {'name': 'Mirca'},
         1: [{'name': 'General'}]},
        {0: {'name': 'Commissioning container'},
         1: [{'name': 'C1S0'}, {'name': 'C1S1'}, {'name': 'C1S2'}, {'name': 'C1S3'}, {'name': 'C2S0'}, {'name': 'C2S1'}, {'name': 'C2S2'}, {'name': 'C2S3'}, {'name': 'C3S0'}, {'name': 'C3S1'}, {'name': 'C3S2'}, {'name': 'C3S3'}, {'name': 'C4S0'}, {'name': 'C4S1'}, {'name': 'C4S2'}, {'name': 'C4S3'}]},
        {0: {'name': 'IT container'},
         1: [{'name': 'General'}]},
        {0: {'name': 'Storage container'},
         1: [{'name': 'General'}]},
        {0: {'name': 'Calp'},
         1: [{'name': 'General'}]},
    ]
    Unit_entries = [
        {
            "name": "Centimeter",
            "short_name": "cm"
        },
        {
            "name": "Meter",
            "short_name": "m"
        },
        {
            "name": "Millimeter",
            "short_name": "mm"
        },
        {
            "name": "Inch",
            "short_name": "in"
        },
        {
            "name": "Foot",
            "short_name": "ft"
        },
        {
            "name": "Square Meter",
            "short_name": "m²"
        },
        {
            "name": "Square Foot",
            "short_name": "ft²"
        },
        {
            "name": "Cubic Meter",
            "short_name": "m³"
        },
        {
            "name": "Cubic Foot",
            "short_name": "ft³"
        },
        {
            "name": "Liter",
            "short_name": "L"
        },
        {
            "name": "Gallon",
            "short_name": "gal"
        },
        {
            "name": "Kilogram",
            "short_name": "kg"
        },
        {
            "name": "Gram",
            "short_name": "g"
        },
        {
            "name": "Pound",
            "short_name": "lb"
        },
        {
            "name": "Ounce",
            "short_name": "oz"
        },
        {
            "name": "Unit",
            "short_name": "unit"
        }
    ]

    Telescope_entries = [
        {"name": "LST1"},
        {"name": "LST2"},
        {"name": "LST3"},
        {"name": "LST4"},
    ]

    Telescope_Structures = [
        {"name": "Drive"},
        {"name": "IT"},
        {"name": "Energy"},
        {"name": "CAT"},
        {"name": "Structure"},
        {"name": "CC"},
    ]

    Payment_entries = [
        {"name": "Common Found"} #Need to incude all
    ]
    Categories_sub_groups_entries = [ #Not finished, just an example
        {0: {"name": "Mount",
             "PBS_code": "8.1.1"},
         1: [{0: {"name": "Lower structure",
                  "PBS_code": "8.1.1.1"},
              1: [{"name": "Central Pin Bearing",
                   "PBS_code": "8.1.1.10.1"},
                  {"name": "Central pin shaft encoder",
                   "PBS_code": "8.1.1.10.2"},
                  {"name": "Central Pin Radial shaft Seal",
                   "PBS_code": "8.1.1.10.3"},
                  {"name": "Heavy bogie's Motor",
                   "PBS_code": "8.1.1.8.1 "},
                  {"name": "Motor's encoder",
                   "PBS_code": "8.1.1.8.2 "},
                  {"name": "Heavy bogie motor's Gearbox",
                   "PBS_code": "8.1.1.8.3"},
                  {"name": "Heavy bogie",
                   "PBS_code": "8.1.1.8.4"},
                  {"name": "Heavy bogie's pinion",
                   "PBS_code": "8.1.1.8.7"},
                  {"name": "Heavy bogie's guiding wheels",
                   "PBS_code": "8.1.1.8.8"},
                  {"name": "Heavy bogie's anti up-lifting wheels",
                   "PBS_code": "8.1.1.8.9"},
                  {"name": "Heavy bogie's Broom & dry lubrication scrapers",
                   "PBS_code": "8.1.1.8.10"},
                  {"name": "Heavy bogie's linear guides",
                   "PBS_code": "8.1.1.8.11"},
                  {"name": "Heavy bogie's spherical joint",
                   "PBS_code": "8.1.1.8.12"},
                  {"name": "Light bogie",
                   "PBS_code": "8.1.1.8.13"},
                  {"name": "Light bogie's guiding wheels",
                   "PBS_code": "8.1.1.8.17"},
                  {"name": "Light bogie's anti up-lifting wheels",
                   "PBS_code": "8.1.1.8.18"},
                  {"name": "Light bogie's Broom & dry lubrication scrapers",
                   "PBS_code": "8.1.1.8.19"},
                  {"name": "Light bogie's linear guides",
                   "PBS_code": "8.1.1.8.20"},
                  {"name": "Light bogie's spherical joint",
                   "PBS_code": "8.1.1.8.21"},
                ]},
                {0: {"name": "Elevation Drive",
                    "PBS_code": "8.1.1.2"},
                1: [{"name": "Drive Gear Bearing",
                    "PBS_code": "8.1.1.2.1"},
                    {"name": "Hand Wheel Bearing",
                    "PBS_code": "8.1.1.2.2"},
                    {"name": "Radial Guiding Wheels",
                    "PBS_code": "8.1.1.2.3"},
                    {"name": "Lateral Guiding Wheels",
                    "PBS_code": "8.1.1.2.4"},
                    {"name": "Chain",
                    "PBS_code": "8.1.1.2.5"},
                    {"name": "Drive gear",
                    "PBS_code": "8.1.1.2.6"},
                    {"name": "Brake",
                    "PBS_code": "8.1.1.2.7"},
                    {"name": "Elevation Drive Inductive Sensor",
                    "PBS_code": "8.1.1.2.8"},
                    {"name": "Motor",
                    "PBS_code": "8.1.1.2.9"},
                    {"name": "Elevation Motor's encoder",
                    "PBS_code": "8.1.1.2.10"},
                    {"name": "Planetary gearbox",
                    "PBS_code": "8.1.1.2.11"},
                    {"name": "Inclinometer",
                    "PBS_code": "8.1.1.2.12"},
                    {"name": "Clutch",
                    "PBS_code": "8.1.1.2.13"},
                    {"name": "Handwheel gearbox",
                    "PBS_code": "8.1.1.2.14"},
                    {"name": "Handwheel clutch",
                    "PBS_code": "8.1.1.2.15"},
                ]}, 
                {0: {"name": "Elevation Bearing",
                    "PBS_code": "8.1.1.3"},
                1: [{"name": "Elevation bearing",
                    "PBS_code": "8.1.1.3.1"},
                    {"name": "Shaft encoder Elevation",
                    "PBS_code": "8.1.1.3.2"},
                ]},
                {0: {"name": "Platform at Elevation Bearing",
                    "PBS_code": "8.1.1.4"},
                1: []},
                {0: {"name": "Stair case up to Elevation Bearing",
                    "PBS_code": "8.1.1.5"},
                1: []},
                {0: {"name": "Platform at Elevation Drive",
                    "PBS_code": "8.1.1.6"},
                1: []},
                {0: {"name": "Bogie Nodes",
                    "PBS_code": "8.1.1.7"},
                1: []},
                {0: {"name": "Bogies",
                    "PBS_code": "8.1.1.8"},
                1: []},
                {0: {"name": "Rail",
                    "PBS_code": "8.1.1.9"},
                1: []},
                {0: {"name": "Central Pin",
                    "PBS_code": "8.1.1.10"},
                1: []},
                {0: {"name": "Azimuth Locking",
                    "PBS_code": "8.1.1.11"},
                1: []},
                {0: {"name": "Azimuth Cable Chain",
                    "PBS_code": "8.1.1.12"},
                1: []},
                {0: {"name": "Elevation Cable Chain",
                    "PBS_code": "8.1.1.13"},
                1: []},
                {0: {"name": "Cable Ducts",
                    "PBS_code": "8.1.1.14"},
                1: []}, 
            ]},
            {0: {"name": "Optical Support Structure",
                "PBS_code": "8.1.2"},
            1: [{0: {"name": "Dish Structure",
                    "PBS_code": "8.1.2.1"},
                1: []},
                {0: {"name": "Elevation Drive Arch and Cables",
                    "PBS_code": "8.1.2.2"},
                1: []},
                {0: {"name": "Camera Support Structure (CSS)",
                    "PBS_code": "8.1.2.3"},
                1: []},
                {0: {"name": "Tension Cables & Anchoring Devices for CSS",
                    "PBS_code": "8.1.2.4"},
                1: []},
                {0: {"name": "Dish Access (stairs, catwalks, safety elements)",
                    "PBS_code": "8.1.2.5"},
                1: []},
                {0: {"name": "Counterweight",
                    "PBS_code": "8.1.2.6"},
                1: []},
                {0: {"name": "Cable Ducts",
                    "PBS_code": "8.1.2.7"},
                1: []},
                ],               
            },
            {0: {"name": "Camera Access Tower",
                "PBS_code": "8.1.3"},
            1: [{0: {"name": "Access Tower Structure",
                    "PBS_code": "8.1.3.1"},
                1: [{"name": "Asynchronous motor",
                "PBS_code": "8.1.3.1.1"},
                {"name": "CAT PLC switch",
                "PBS_code": "8.1.3.1.10"},
                {"name": "Inductive position Sensor",
                "PBS_code": "8.1.3.1.11"},
                {"name": "Inductive speed Sensor",
                "PBS_code": "8.1.3.1.12"},
                {"name": "Vulkolan-Rolls (friction-wheel)",
                "PBS_code": "8.1.3.1.13"},
                {"name": "Vulkolan-Rolls (driven-wheel)",
                "PBS_code": "8.1.3.1.14"},
                {"name": "Vulkolan-Rolls (guide-roller)",
                "PBS_code": "8.1.3.1.15"},
                {"name": "Bearing for rolls",
                "PBS_code": "8.1.3.1.16"},
                {"name": "CAT Clutch",
                "PBS_code": "8.1.3.1.17"},
                {"name": "LOGO! TDE 1",
                "PBS_code": "8.1.3.1.18"},
                {"name": "LOGO! TDE 2",
                "PBS_code": "8.1.3.1.2"},
                {"name": "Gearbox",
                "PBS_code": "8.1.3.1.2"},
                {"name": "Key switch",
                "PBS_code": "8.1.3.1.23"},
                {"name": "Door closing sensor",
                "PBS_code": "8.1.3.1.24"},
                {"name": "Camera rear maintenance scaffold sensor",
                "PBS_code": "8.1.3.1.25"},
                {"name": "Camera front maintenance scaffold sensor",
                "PBS_code": "8.1.3.1.26"},
                {"name": "Frequency inverter",
                "PBS_code": "8.1.3.1.3"},
                {"name": "Camera access tower PLC",
                "PBS_code": "8.1.3.1.4"},
                {"name": "Camera access tower CSS PLC ",
                "PBS_code": "8.1.3.1.5"},
                {"name": "CAT PLC I/O module",
                "PBS_code": "8.1.3.1.6"},
                {"name": "CAT CSS PLC I/O module",
                "PBS_code": "8.1.3.1.7"},
                {"name": "CAT cabinet I/O module",
                "PBS_code": "8.1.3.1.8"},
                {"name": "CAT cabinet I/O module power distribution",
                "PBS_code": "8.1.3.1.9"},
                ]},
                {0: {"name": "Arch Locking System",
                    "PBS_code": "8.1.3.2"},
                1: [{"name": "Locking clamps",
                "PBS_code": "8.1.3.2.1"},
                {"name": "Locking Actuator",
                "PBS_code": "8.1.3.2.2"},
                {"name": "Current reduction (locking actuator)",
                "PBS_code": "8.1.3.2.3"},
                {"name": "Locking sensors",
                "PBS_code": "8.1.3.2.4"},
                {"name": "Proximity sensor",
                "PBS_code": "8.1.3.2.5"},
                ]},
                ],               
            },
            {0: {"name": "Primary Mirror",
                "PBS_code": "8.2.1"},
            1: [{0: {"name": "Mirror Facets",
                    "PBS_code": "8.2.1.1"},
                1: []},
                {0: {"name": "Mirror Supporting Pads",
                    "PBS_code": "8.2.1.2"},
                1: []},
                ],               
            },
            {0: {"name": "Optics Alignment",
                "PBS_code": "8.2.2"},
            1: [{0: {"name": "Actuators",
                    "PBS_code": "8.2.2.1"},
                1: [{"name": "AMC box power relay",
                "PBS_code": "8.2.2.10"},
                {"name": "SFP optical switch - PoE 1",
                "PBS_code": "8.2.2.11"},
                {"name": "SFP optical switch - PoE 2",
                "PBS_code": "8.2.2.12"},]},
                {0: {"name": "Interface Plates",
                    "PBS_code": "8.2.2.2"},
                1: []},
                {0: {"name": "AMC Control & Power Boxes",
                    "PBS_code": "8.2.2.3"},
                1: [{"name": "SFP optical switch",
                "PBS_code": "8.2.2.3.0"},
                {"name": "XBee module",
                "PBS_code": "8.2.2.3.1"},
                {"name": "NUC PC (Intel)",
                "PBS_code": "8.2.2.3.2"},
                {"name": "Antenna",
                "PBS_code": "8.2.2.3.3"},
                ]},
                {0: {"name": "AMC Cameras",
                    "PBS_code": "8.2.2.4"},
                1: []},
                {0: {"name": "AMC Cabling",
                    "PBS_code": "8.2.2.5"},
                1: [{"name": "AMC box power cable",
                "PBS_code": "8.2.2.5.1"},
                {"name": "AMC box signal cable",
                "PBS_code": "8.2.2.5.2"},
                ]},
                {0: {"name": "AMC Main Cabinet",
                    "PBS_code": "8.2.2.6"},
                1: [{"name": "AMC box signal cable",
                "PBS_code": "8.2.2.6.1"},
                {"name": "Calibox power relay",
                "PBS_code": "8.2.2.6.10"},
                {"name": "Calibox laser power relay",
                "PBS_code": "8.2.2.6.11"},
                {"name": "PSF camera power relay",
                "PBS_code": "8.2.2.6.12"},
                {"name": "Main power power relay",
                "PBS_code": "8.2.2.6.13"},
                {"name": "400V breaker",
                "PBS_code": "8.2.2.6.14"},
                {"name": "230V breaker",
                "PBS_code": "8.2.2.6.15"},
                {"name": "Central Dish Cabinet 24V PS",
                "PBS_code": "8.2.2.6.2"},
                {"name": "Central Dish Cabinet NMEA2000/Profinet module",
                "PBS_code": "8.2.2.6.4"},
                {"name": "Central Dish Cabinet Switch",
                "PBS_code": "8.2.2.6.5"},
                {"name": "Central Dish Cabinet Profinet switch",
                "PBS_code": "8.2.2.6.6"},
                {"name": "Central Dish Cabinet IO module",
                "PBS_code": "8.2.2.6.7"},
                {"name": "CDM PC power relay",
                "PBS_code": "8.2.2.6.8"},
                {"name": "SG power relay",
                "PBS_code": "8.2.2.6.9"},
                ]},
                ],               
            },
            {0: {"name": "Mechanics Structure",
                "PBS_code": "8.3.1"},
            1: [{0: {"name": "Camera Body",
                    "PBS_code": "8.3.1.1"},
                1: [{"name": "Main Structure",
                    "PBS_code": "8.3.1.1.1"},
                    {"name": "PMT Modules Holder",
                    "PBS_code": "8.3.1.1.2"},
                    {"name": "Modules Mechanical Structure",
                    "PBS_code": "8.3.1.1.3"},
                    {"name": "Auxiliary electronics mechanic support",
                    "PBS_code": "8.3.1.1.4"},
                    {"name": "Camera Cabling System",
                    "PBS_code": "8.3.1.1.5"},
                    {"name": "Internal Walls",
                    "PBS_code": "8.3.1.1.6"},]},
                {0: {"name": "Camera Fixation",
                    "PBS_code": "8.3.1.2"},
                1: []},
                {0: {"name": "Camera Enclosure",
                    "PBS_code": "8.3.1.3"},
                1: [{"name": "Camera Skin",
                    "PBS_code": "8.3.1.3.1"},
                    {"name": "Back Door",
                    "PBS_code": "8.3.1.3.2"},
                    {"name": "External Patch Panel",
                    "PBS_code": "8.3.1.3.3"},]},
                {0: {"name": "Camera Front Door",
                    "PBS_code": "8.3.1.4"},
                1: [{"name": "Camera Shutter",
                    "PBS_code": "8.3.1.4.1"},
                    {"name": "Entrance Window",
                    "PBS_code": "8.3.1.4.2"},
                    {"name": "Targets for Displacement Monitor",
                    "PBS_code": "8.3.1.4.3"},
                    {"name": "Support for LEDs and DM targets",
                    "PBS_code": "8.3.1.4.4"},
                    {"name": "Mechanics for the Camera Front Door",
                    "PBS_code": "8.3.1.4.5"},
                    {"name": "Hydraulic System",
                    "PBS_code": "8.3.1.4.6"},]},
                {0: {"name": "Star Imaging Screen",
                    "PBS_code": "8.3.1.5"},
                1: [{"name": "Star imaging screen moving mechanism",
                    "PBS_code": "8.3.1.5.1"},
                    ]},
                ],               
            },
            {0: {"name": "Focal Plane Instrumentation",
                "PBS_code": "8.3.2"},
            1: [{0: {"name": "Light Guides",
                    "PBS_code": "8.3.2.1"},
                1: []},
                {0: {"name": "Photosensors",
                    "PBS_code": "8.3.2.2"},
                1: [{"name": "PMT + HV board",
                    "PBS_code": "8.3.2.2.1"},
                    {"name": "Shield",
                    "PBS_code": "8.3.2.2.2"},]},
                {0: {"name": "Preamplifier Board",
                    "PBS_code": "8.3.2.3"},
                1: [{"name": "PACTA",
                    "PBS_code": "8.3.2.3.1"},
                    {"name": "Preamplifier PCB",
                    "PBS_code": "8.3.2.3.2"},]},
                {0: {"name": "FPI Slow Control Board",
                    "PBS_code": "8.3.2.4"},
                1: []},
                ],               
            },
            {0: {"name": "Signal Processing",
                "PBS_code": "8.3.3"},
            1: [{0: {"name": "Readout Board",
                    "PBS_code": "8.3.3.1"},
                1: []},
                {0: {"name": "L0L1 Trigger",
                    "PBS_code": "8.3.3.2"},
                1: [{"name": "L0 ASIC",
                    "PBS_code": "8.3.3.2.1"},
                    {"name": "L1 ASIC",
                    "PBS_code": "8.3.3.2.2"},
                    {"name": "L0L1 mezzanine",
                    "PBS_code": "8.3.3.2.3"},]},
                {0: {"name": "Backplane",
                    "PBS_code": "8.3.3.3"},
                1: []},
                {0: {"name": "Trigger Interface Board",
                    "PBS_code": "8.3.3.4"},
                1: []},
                ],               
            },
            {0: {"name": "Camera Auxiliary Systems",
                "PBS_code": "8.3.4"},
            1: [{0: {"name": "Ethernet Switches",
                    "PBS_code": "8.3.4.1"},
                1: []},
                {0: {"name": "Power Distribution System",
                    "PBS_code": "8.3.4.2"},
                1: [{"name": "Power Supply Box",
                    "PBS_code": "8.3.4.2.1"},
                    {"name": "Power Distribution Box",
                    "PBS_code": "8.3.4.2.2"},
                    {"name": "Bus Bars",
                    "PBS_code": "8.3.4.2.3"},]},
                {0: {"name": "Environmental Control",
                    "PBS_code": "8.3.4.3"},
                1: [{"name": "Cooling System",
                    "PBS_code": "8.3.4.3.1"},
                    {"name": "Dehumidification",
                    "PBS_code": "8.3.4.3.2"},
                    {"name": "Pressure Control",
                    "PBS_code": "8.3.4.3.3"},]},
                {0: {"name": "Embedded Camera Controller",
                    "PBS_code": "8.3.4.4"},
                1: [{"name": "Compact RiO",
                    "PBS_code": "8.3.4.4.1"},
                    {"name": "Reference LEDs",
                    "PBS_code": "8.3.4.4.2"},]},
                {0: {"name": "UCTS Auxiliary",
                    "PBS_code": "8.3.4.5"},
                1: []},
                {0: {"name": "Camera Cabling",
                    "PBS_code": "8.3.4.6"},
                1: [{"name": "Camera Internal Cabling",
                    "PBS_code": "8.3.4.6.1"},
                    {"name": "Camera External Cabling",
                    "PBS_code": "8.3.4.6.2"},]},
                {0: {"name": "External Cooling Unit",
                    "PBS_code": "8.3.4.7"},
                1: []},
                {0: {"name": "Camera Server",
                    "PBS_code": "8.3.4.8"},
                1: []},
                {0: {"name": "Central CCD Camera Pixel",
                    "PBS_code": "8.3.4.9"},
                1: []},
                {0: {"name": "Hydraulic Pump",
                    "PBS_code": "8.3.4.10"},
                1: []},
                {0: {"name": "Transportation and Installation Tool",
                    "PBS_code": "8.3.4.11"},
                1: []},
                ],               
            },
            {0: {"name": "Energy Storage",
                "PBS_code": "8.4.1"},
            1: [{0: {"name": "UPS Container",
                     "PBS_code": "8.4.1.1"},
                 1:[{"name": "UC PLC 1",
                "PBS_code": "8.4.1.1.1"},
                {"name": "CC PLC",
                "PBS_code": "8.4.1.1.10"},
                {"name": "CC switch",
                "PBS_code": "8.4.1.1.11"},
                {"name": "PAC",
                "PBS_code": "8.4.1.1.12"},
                {"name": "UPS",
                "PBS_code": "8.4.1.1.13"},
                {"name": "Flywheel",
                "PBS_code": "8.4.1.1.14"},
                {"name": "UC PLC DI module",
                "PBS_code": "8.4.1.1.2"},
                {"name": "UC PLC AI module",
                "PBS_code": "8.4.1.1.3"},
                {"name": "UC PLC 2 (ICRR)",
                "PBS_code": "8.4.1.1.4"},
                {"name": "UC PLC 2 DO module",
                "PBS_code": "8.4.1.1.5"},
                {"name": "UC switch",
                "PBS_code": "8.4.1.1.6"},
                {"name": "UC Modbus gateway",
                "PBS_code": "8.4.1.1.7"},
                {"name": "UC tepm&hum sensor",
                "PBS_code": "8.4.1.1.8"},
                {"name": "UC PLC 2 relay",
                "PBS_code": "8.4.1.1.9"},]}
            ],               
            },
            {0: {"name": "Lightning Protection",
                "PBS_code": "8.4.2"},
            1: [],               
            },
            {0: {"name": "Calibration and Pointing Control",
                "PBS_code": "8.4.3"},
            1: [{0: {"name": "Camera Displacement Monitoring and Star Guider Hood",
                    "PBS_code": "8.4.3.1"},
                1: []},
                {0: {"name": "Camera Displacement Monitoring",
                    "PBS_code": "8.4.3.2"},
                1: [{"name": "CDM CCD Camera",
                "PBS_code": "8.4.3.2.1"},
                {"name": "Temperature/Humidity sensor",
                "PBS_code": "8.4.3.2.2"},
                {"name": "CDM control PC",
                "PBS_code": "8.4.3.2.3"},
                {"name": "CDM & Star guider housing",
                "PBS_code": "8.4.3.2.4"},]},
                {0: {"name": "Starguider",
                    "PBS_code": "8.4.3.3"},
                1: [{"name": "Star guider camera",
                "PBS_code": "8.4.3.3.1"},
                {"name": "Calibration LEDs",
                "PBS_code": "8.4.3.3.2"},]},
                {0: {"name": "Optical Axis Reference Laser",
                    "PBS_code": "8.4.3.4"},
                1: [{"name": "OARL housing",
                "PBS_code": "8.4.3.4.1"},
                {"name": "DC/DC converter",
                "PBS_code": "8.4.3.3.2"},
                {"name": "light source (laser)",
                "PBS_code": "8.4.3.3.3"},]},
                {0: {"name": "Calibration Light Source",
                    "PBS_code": "8.4.3.5"},
                1: [{"name": "Calibox housing",
                "PBS_code": "8.4.3.5.1"},
                {"name": "Calibox Webcam",
                "PBS_code": "8.4.3.5.2"},
                {"name": "Cali box laser",
                "PBS_code": "8.4.3.5.3"},
                {"name": "Cali box PC",
                "PBS_code": "8.4.3.5.4"},]},
                {0: {"name": "Distance Meter",
                    "PBS_code": "8.4.3.6"},
                1: []},
                {0: {"name": "PSF Camera",
                    "PBS_code": "8.4.3.7"},
                1: []},
                ],               
            },
            {0: {"name": "Drive Control System",
                "PBS_code": "8.4.4"},
            1: [{0: {"name": "Main Drive Control System",
                    "PBS_code": "8.4.4.1"},
                1: [{"name": "Drive PLC",
                "PBS_code": "8.4.4.1.1"},
                {"name": "Safety PLC",
                "PBS_code": "8.4.4.1.2"},
                {"name": "Braking module (Elevation)",
                "PBS_code": "8.4.4.1.10"},
                {"name": "Profibus module (motor control unit)",
                "PBS_code": "8.4.4.1.14"},
                {"name": "Profibus module",
                "PBS_code": "8.4.4.1.15"},
                {"name": "Drive control I/O module",
                "PBS_code": "8.4.4.1.16"},
                {"name": "Profinet gateway (Inclinometer)",
                "PBS_code": "8.4.4.1.17"},
                {"name": "Main Drive Control System Fence sensors",
                "PBS_code": "8.4.4.1.18"},
                {"name": "CTAO Communication/ control",
                "PBS_code": "8.4.4.1.19"},
                {"name": "PC for the control software/servers",
                "PBS_code": "8.4.4.1.20"},
                {"name": "Rackable optical switch",
                "PBS_code": "8.4.4.1.22"},
                {"name": "Drive Key switch",
                "PBS_code": "8.4.4.1.24"},
                {"name": "Drive Electric hardware",
                "PBS_code": "8.4.4.1.25"},
                {"name": "Azimuth 24 V  power supply",
                "PBS_code": "8.4.4.1.26"},
                {"name": "Elevation 24 V power supply",
                "PBS_code": "8.4.4.1.27"},
                {"name": "24 V Drive PLC distribution",
                "PBS_code": "8.4.4.1.28"},
                {"name": "24 V Safety PLC distribution",
                "PBS_code": "8.4.4.1.29"},
                {"name": "PLC Server",
                "PBS_code": "8.4.4.1.3"},
                {"name": "24 V PLC Server distribution",
                "PBS_code": "8.4.4.1.30"},
                {"name": "ALS 24 V PS",
                "PBS_code": "8.4.4.1.31"},
                {"name": "ELS 24 V PS",
                "PBS_code": "8.4.4.1.32"},
                {"name": "Azimuth Power Unit",
                "PBS_code": "8.4.4.1.33"},
                {"name": "Elevation Power Unit",
                "PBS_code": "8.4.4.1.34"},
                {"name": "Drive Surge protection device",
                "PBS_code": "8.4.4.1.35"},
                {"name": "Control Unit (Azimuth)",
                "PBS_code": "8.4.4.1.4"},
                {"name": "Control Unit (Elevation)",
                "PBS_code": "8.4.4.1.5"},
                {"name": "Motor module (Azimuth)",
                "PBS_code": "8.4.4.1.6"},
                {"name": "Braking module (Azimuth)",
                "PBS_code": "8.4.4.1.7"},
                {"name": "Motor module (Elevation)",
                "PBS_code": "8.4.4.1.9"},
                ]},
                {0: {"name": "Encoders",
                    "PBS_code": "8.4.4.2"},
                1: []},
                {0: {"name": "Azimuth",
                    "PBS_code": "8.4.4.3"},
                1: [{"name": "Az Gearbox",
                "PBS_code": "8.4.5.3.1"},]},
                {0: {"name": "Elevation",
                    "PBS_code": "8.4.4.4"},
                1: [{"name": "Elevation Gearbox",
                "PBS_code": "8.4.4.4.1"},
                {"name": "Elevation Brake",
                "PBS_code": "8.4.4.4.2"},
                {"name": "Elevation Bolt",
                "PBS_code": "8.4.4.4.3"},]},
                {0: {"name": "Precision Inclinometer",
                    "PBS_code": "8.4.4.5"},
                1: []},
                {0: {"name": "Drive Cables",
                    "PBS_code": "8.4.4.6"},
                1: []},
                {0: {"name": "End-switches and Interlocks",
                    "PBS_code": "8.4.4.7"},
                1: [{"name": "Main Drive Control System Safety edge sensor (Azimuth)",
                "PBS_code": "8.4.4.7.1"},
                {"name": " Main Drive Control System Safety edge sensor (Elevation)",
                "PBS_code": "8.4.4.7.2"},]},
                ],               
            },
            {0: {"name": "Drive Container",
                "PBS_code": "8.4.5"},
            1: [{0: {"name": "Container",
                    "PBS_code": "8.4.5.1"},
                1: [{"name": "Drive container Air-conditioning/cooling",
                "PBS_code": "8.4.5.1.1"}]},
                {0: {"name": "Racks",
                    "PBS_code": "8.4.5.2"},
                1: [{"name": "Rackable PC",
                "PBS_code": "8.4.5.2.1"},
                {"name": "Rackable switch",
                "PBS_code": "8.4.5.2.2"},
                {"name": "Rackable UPS",
                "PBS_code": "8.4.5.2.3"}]},
                {0: {"name": "UPS",
                    "PBS_code": "8.4.5.3"},
                1: []},
                ],               
            },
            {0: {"name": "Structure Condition Monitoring",
                "PBS_code": "8.4.6"},
            1: [{0: {"name": "Accelerometers",
                    "PBS_code": "8.4.6.1"},
                1: []},
                {0: {"name": "Strain Gauges",
                    "PBS_code": "8.4.6.2"},
                1: []},
                {0: {"name": "Readout of Structure Condition",
                    "PBS_code": "8.4.6.3"},
                1: []},
                {0: {"name": "Structure Condition Cabling",
                    "PBS_code": "8.4.6.4"},
                1: []},
                {0: {"name": "CSS Load Pins",
                    "PBS_code": "8.4.6.5"},
                1: [{"name": "Load Pins",
                "PBS_code": "8.4.6.5.1"},
                {"name": "Readout of Load Pins",
                "PBS_code": "8.4.6.5.2"},
                {"name": "Load Pin Cabling",
                "PBS_code": "8.4.6.5.3"},]},
                ],               
            },
            {0: {"name": "Cabling Structures",
                "PBS_code": "8.4.7"},
            1: [{0: {"name": "Main Electrical Cabinet",
                    "PBS_code": "8.4.7.1"},
                1: [{"name": "Electric hardware",
                "PBS_code": "8.4.7.1.1"},
                {"name": "24 V power supply",
                "PBS_code": "8.4.7.1.2"}]},
                {0: {"name": "Structure Cabinets",
                    "PBS_code": "8.4.7.2"},
                1: [{"name": "Spring terminal cabinet 30",
                "PBS_code": "8.4.7.2.1"},
                {"name": "Spring terminal cabinet 40",
                "PBS_code": "8.4.7.2.2"},
                {"name": "Spring terminal cabinet 42",
                "PBS_code": "8.4.7.2.3"},
                {"name": "Spring terminal cabinet 62",
                "PBS_code": "8.4.7.2.4"},
                {"name": "Spring terminal bogies monitoring cabinet",
                "PBS_code": "8.4.7.2.5"}]},
                {0: {"name": "Structure Cables",
                    "PBS_code": "8.4.7.3"},
                1: []},
                {0: {"name": "Access Tower Platform Cabinet",
                    "PBS_code": "8.4.7.4"},
                1: []},
                ],               
            },
    ]

    admin_groups_entries = [
        {"name": "admin"},
        {"name": "technician"},
        {"name": "user"},
    ]

    print("Adding data into DB...")

    if not Stock_Type.objects.exists():
        for entry in StockTypes_entries:
            Stock_Type.objects.get_or_create(**entry)
    else:
        print("There was data on stock types.")

    if not Item_status.objects.exists():
        for entry in ItemStatuses_entries:
            Item_status.objects.get_or_create(**entry)
    else:
        print("There was data on item status.")

    if not Purchase_status.objects.exists():
        for entry in PurchaseStatuses_entries:
            Purchase_status.objects.get_or_create(**entry)
    else:
        print("There was data on purchase status.")
    
    if not Location.objects.exists() and not Zone.objects.exists():
        for entry in  Location_zones_entries:
            location, success = Location.objects.get_or_create(**entry[0])
            for zone in entry[1]:
                zone['location'] = location
                Zone.objects.get_or_create(**zone)
    else:
        print("There was data on location or zone.")

    if not Telescope.objects.exists():
        for entry in Telescope_entries:
            telescope, success = Telescope.objects.get_or_create(**entry)
            for data in Telescope_Structures:
                if len(Telescope.objects.all()) == 1 and data['name'] == "CC":
                    Telescope_structure.objects.get_or_create(
                        name=data['name'], 
                        telescope=telescope
                    )
                else:
                    Telescope_structure.objects.get_or_create(
                        name=data['name'], 
                        telescope=telescope
                    )

    else:
        print("There was data on telescope.")

    if not Unit.objects.exists():
        for entry in Unit_entries:
            Unit.objects.get_or_create(**entry)
    else:
        print("There was data on unit.")

    if not Payment_sources.objects.exists():
        for entry in Payment_entries:
            Payment_sources.objects.get_or_create(**entry)
    else:
        print("There was data on payment source.")
        
    if not Category.objects.exists() and not Sub_category.objects.exists() and not Group.objects.exists():
        for entry in Categories_sub_groups_entries:
            category, success = Category.objects.get_or_create(**entry[0])
            for sub in entry[1]:
                sub[0]["category"] = category
                sub_category, success = Sub_category.objects.get_or_create(**sub[0])
                for group in sub[1]:
                    group["sub_category"] = sub_category
                    Group.objects.get_or_create(**group)
    else:
        print("There was data on category, sub-category or group.")

    if not G.objects.exists():
        for index, entry in enumerate(admin_groups_entries):
            group, success = G.objects.get_or_create(**entry)
            if entry['name'] == 'admin':
                users = User.objects.filter(is_superuser=True)
                for user in users:
                    user.groups.add(group)
                    user.save()
            if index == 0:
                all_permission = Permission.objects.all()
                group.permissions.set(all_permission)
            elif index == 1:
                view_permissions = Permission.objects.filter(codename__startswith='view_')
                other_permissions = Permission.objects.filter(codename__in=["add_item", "change_item", "add_stock", "change_stock"])
                group.permissions.set(view_permissions)
                group.permissions.add(*other_permissions)
            else:
                view_permissions = Permission.objects.filter(codename__startswith='view_')
                group.permissions.set(view_permissions)

    else:
        print("There was data on auth group.")

    print("Done!")
