# Generated by Django 4.2.9 on 2024-08-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='PBS_code',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='PBS_code',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='sub_category',
            name='PBS_code',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
