# Generated by Django 4.2.9 on 2024-08-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_category_pbs_code_group_pbs_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/'),
        ),
        migrations.AlterField(
            model_name='telescope',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/'),
        ),
    ]
