# Generated by Django 4.2.9 on 2024-08-20 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_purchase_quantity_stock_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='type',
            new_name='stock_type',
        ),
    ]
