# Generated by Django 4.2.9 on 2024-09-03 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_type_stock_stock_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='supplier',
        ),
        migrations.AddField(
            model_name='purchase_group',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier'),
        ),
    ]
