# Generated by Django 4.2.9 on 2024-09-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_purchase_supplier_purchase_group_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='quantity',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='purchase_group',
            name='standard_lead_time',
            field=models.IntegerField(default=7, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
