# Generated by Django 4.2.9 on 2024-09-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_purchase_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_group',
            name='order_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
