# Generated by Django 4.2.9 on 2024-09-23 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_purchase_group_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='old',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.CreateModel(
            name='Telescope_structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telescope', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.telescope')),
            ],
        ),
    ]
