# Generated by Django 4.2.9 on 2024-09-23 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_stock_old_telescope_structure'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='telescope_structure',
            table='telescope_structures',
        ),
    ]
