# Generated by Django 4.2.9 on 2024-09-27 08:17

from django.db import migrations, models
import django.db.models.deletion
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_item_telescope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.ForeignKey(default=inventory.models.get_unmanaged_status, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.item_status'),
        ),
    ]
