# Generated by Django 4.2.9 on 2024-10-10 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_category_options_alter_item_status_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='minimum_stock',
        ),
        migrations.RemoveField(
            model_name='item',
            name='code',
        ),
        migrations.RemoveField(
            model_name='item',
            name='group',
        ),
        migrations.CreateModel(
            name='partNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=150)),
                ('minimum_stock', models.SmallIntegerField(blank=True, null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.group')),
            ],
            options={
                'verbose_name': 'Part Number',
                'verbose_name_plural': 'Part Numbers',
                'db_table': 'partNumber',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='partNumber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.partnumber'),
        ),
    ]
