# Generated by Django 4.2.9 on 2024-10-10 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_remove_group_minimum_stock_remove_item_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnumber',
            old_name='part_number',
            new_name='code',
        ),
    ]
