# Generated by Django 4.2.9 on 2024-10-11 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_rename_part_number_partnumber_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='partNumber',
            new_name='part_number',
        ),
    ]
