# Generated by Django 4.2.9 on 2024-10-11 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_rename_partnumber_item_part_number'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='partnumber',
            table='part_number',
        ),
    ]
